### ISSUE TITLE
Lets list all of the weaknesses and strengths here

### ISSUE THREAD

**Issue by CounterfeitLlama** [PolturonduckenApp/Elemental-Tower-Defense#1]
So if I understand correctly, the towers are trying to stop the shadow people from stealing the elements from us? If so, what things like armor, etc. could the enemies wear to change the effects of the towers? For example, a rocky armor would make the different fire towers be weak against the enemy, but the different water towers be strong against the rock armor. Wind towers would probably be unaffected, and I don't know about rock towers. This is just an example, what do you guys think?

**Comment by DataManiac18** [comment]
Yahoodle!

**Comment by DataManiac18** [comment]
So elements are: Wind, Fire, Water, Earth/Rock

We could go with Fire beats Wind, Water beats Fire, Earth beats Water, and Wind beats Earth. 

Many options for what beats what and a case can be made for all, so we could just pick one order eh.

**Comment by rpolhemus** [comment]
my impression of what has been said (no opinion - open to any change) was that the enemies were shadow, and the towers were elemental -

**Comment by DataManiac18** [comment]
Right I agree. I was originally thinking that the certain enemies with water/fire/etc resistant armor would need to be "beat" by the element that defeats it,  but I realize now that it would be more understandable and user friendly just for anything but (insert elemental type of the resistant armor) would beat that enemy

**Comment by DataManiac18** [comment]
Just brief, ignore this:
https://cloud.githubusercontent.com/assets/17730200/14973148/635213e6-10b2-11e6-9d0f-8868a2c0d20d.jpg
t:
https://cloud.githubusercontent.com/assets/17730200/14973169/9549c9ac-10b2-11e6-9a55-2f4270685d3c.png
